apiVersion: v1
kind: Service
metadata:
  name: sdm-gateway-{{MYVARNAME}}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 5000
  selector:
    app: sdm-gateway-{{MYVARNAME}}
