on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@master
      - 
        name: "Install Kubelogin"
        run: |
            echo \"Install Kubelogin\"
            echo \"Downloading Zip\"
            wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
            echo \"Unzipping kubelogin\"
            unzip kubelogin-linux-amd64.zip
            sudo mv ./bin/linux_amd64/kubelogin /usr/bin
      - 
        name: "Generate kube to connect with AKS."
        run: |
             az login --service-principal -u ${{secrets.SPN_CLIENT_ID}}  -p ${{secrets.SPN_CLIENT_SECRET}} --tenant ${{secrets.SPN_CLIENT_TENANT}}
             az account set --subscription ${{secrets.SPN_SUBSCRIPTION_ID}}
             echo "running creds"
             az aks get-credentials --resource-group ${{secrets.SPN_RG_NM}} --name ${{secrets.SPN_AKS_NM}}
             export KUBECONFIG=/home/runner/.kube/config
             kubelogin convert-kubeconfig -l spn 
             kubectl cluster-info
             kubectl config set-context --current --namespace=${{secrets.NAMESPACE}}
      -
        name: "Deploy AKS Service"
        run: |
            kubectl apply -f /gatewayService3.yaml
