on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@master
      - 
        name: "Install Kubelogin"
        run: |
            echo \"Install Kubelogin\"
            echo \"Downloading Zip\"
            wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
            echo \"Unzipping kubelogin\"
            unzip kubelogin-linux-amd64.zip
            sudo mv ./bin/linux_amd64/kubelogin /usr/bin
      - 
        name: "Generate kube to connect with AKS."
        run: |
             az login --service-principal -u ${{secrets.SPN_CLIENT_ID}}  -p ${{secrets.SPN_CLIENT_SECRET}} --tenant ${{secrets.SPN_CLIENT_TENANT}}
             az account set --subscription ${{secrets.SPN_SUBSCRIPTION_ID}}
             echo "running creds"
             az aks get-credentials --resource-group ${{secrets.SPN_RG_NM}} --name ${{secrets.SPN_AKS_NM}}
             export KUBECONFIG=/home/runner/.kube/config
             kubelogin convert-kubeconfig -l spn 
             kubectl cluster-info
             kubectl config set-context --current --namespace=${{secrets.NAMESPACE}}
      -
        name: "Deploy AKS Service"
        run: |
            kubectl apply -f gatewayService3.yaml
  
      -
        name: "Create SDM Gateway"
        id: create-sdm-gateway
        run: |
            wget -O sdm-cli.zip https://app.strongdm.com/releases/cli/linux
            unzip sdm-cli.zip
            ./sdm login --admin-token=${{secrets.SDM_ADMIN_TOKEN}}
            RELAYTOKEN=$(sudo ./sdm relay  create-gateway --name="TestGateway123" 10.0.0.1:443 0.0.0.0:5000)
            echo $RELAYTOKEN
            echo '::set-output name=token::$RELAYTOKEN'
            
      -
        name: "Read certificate from KeyVault"
        run: |
          cert=$(az keyvault secret show --name "strongdmcert" --vault-name "keyvaultstrongdm" --query "value" | sed 's/^.//;s/.$//')
          certKey=$(az keyvault secret show --name "strongdmkey" --vault-name "keyvaultstrongdm" --query "value" | sed 's/^.//;s/.$//')
          echo $cert
          echo "action_state=$cert" >> $GITHUB_ENV
          
      -
        name: "Create Kubernet Secrets"
        run: |
          echo $cert
          echo "${{ env.action_state }}"
          echo "${{ steps.create-sdm-gateway.outputs.token }}"
          kubectl create secret generic sdm-gateway-secret-3 --from-literal=tls.key=$certKey --from-literal=tls.crt=$cert --from-literal=token=${{steps.create-sdm-gateway.outputs.token}}
