on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    env:
      GATEWAY_NUMBER: 6
      GATEWAY_NAME: TEST-NPE-GATEWAY-
      KEY_VAULT_NAME: keyvaultstrongdm
      CERT_VAULT_PATH: strongdmcert
      KEY_VAULT_PATH: strongdmkey
    
    steps: 
      - 
        uses: actions/checkout@master
      - 
        name: "Install Kubelogin"
        run: |
            echo \"Install Kubelogin\"
            echo \"Downloading Zip\"
            wget https://github.com/Azure/kubelogin/releases/download/v0.0.9/kubelogin-linux-amd64.zip
            echo \"Unzipping kubelogin\"
            unzip kubelogin-linux-amd64.zip
            sudo mv ./bin/linux_amd64/kubelogin /usr/bin
      - 
        name: "Generate kube to connect with AKS."
        run: |
             az login --service-principal -u ${{secrets.SPN_CLIENT_ID}}  -p ${{secrets.SPN_CLIENT_SECRET}} --tenant ${{secrets.SPN_CLIENT_TENANT}}
             az account set --subscription ${{secrets.SPN_SUBSCRIPTION_ID}}
             echo "running creds"
             az aks get-credentials --resource-group ${{secrets.SPN_RG_NM}} --name ${{secrets.SPN_AKS_NM}}
             export KUBECONFIG=/home/runner/.kube/config
             kubelogin convert-kubeconfig -l spn 
             kubectl cluster-info
             kubectl config set-context --current --namespace=${{secrets.NAMESPACE}}
             
      -
        name: "Deploy AKS Service"
        if: ${{ false }}
        run: |
            MYVAR=4
            cat gatewayService3.yaml | sed "s/{{MYVARNAME}}/${{ env.GATEWAY_NUMBER }}/g" | kubectl apply -f -
            
      - 
        name: Sleep for 30 seconds
        if: ${{ false }}
        run: sleep 360s
      
      -
        name: "Create SDM Gateway"
        if: ${{ false }}
        id: create-sdm-gateway
        run: |
            wget -O sdm-cli.zip https://app.strongdm.com/releases/cli/linux
            unzip sdm-cli.zip
            ./sdm login --admin-token=${{secrets.SDM_ADMIN_TOKEN}}
            gatewayname="${{ env.GATEWAY_NAME }}${{ env.GATEWAY_NUMBER }}"
            echo $gatewayname
            RELAYTOKEN=$(sudo ./sdm relay  create-gateway --name=$gatewayname 10.0.0.1:443 0.0.0.0:5000)
            echo $RELAYTOKEN
            echo "RELAYTOKEN=$RELAYTOKEN" >> $GITHUB_ENV
            
      -
        name: "Read certificate from KeyVault"
        run: |
          cert=$(az keyvault secret show --name ${{ env.CERT_VAULT_PATH }} --vault-name ${{ env.KEY_VAULT_NAME }} --query "value" | sed 's/^.//;s/.$//')
          certKey=$(az keyvault secret show --name ${{ env.KEY_VAULT_PATH }} --vault-name ${{ env.KEY_VAULT_NAME }} --query "value" | sed 's/^.//;s/.$//')
          echo $cert
          echo "cert=$cert" >> $GITHUB_ENV
          echo "certKey=$certKey" >> $GITHUB_ENV
          
      -
        name: "Create Kubernet Secrets"
        if: ${{ false }}
        run: |
          secretname="sdm-gateway-secret-${{ env.GATEWAY_NUMBER }}"
          echo $secretname
          kubectl create secret generic $secretname --from-literal=tls.key=${{ env.certKey}} --from-literal=tls.crt=${{ env.cert}} --from-literal=token=${{ env.RELAYTOKEN }}

      -
        name: "Deploy Kubernet Gateway"
        if: ${{ false }}
        run: |
          cat gatewayDep3.yaml | sed "s/{{MYVARNAME}}/${{ env.GATEWAY_NUMBER }}/g" | kubectl apply -f -
